In [1]:
# libraries
import pandas as pd

# fbref table link
url_df = 'https://fbref.com/en/comps/Big5/shooting/players/Big-5-European-Leagues-Stats'

df = pd.read_html(url_df)
df

[     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                      Rk             Player             Nation
 0                     1         Max Aarons            eng ENG
 1                     2   Brenden Aaronson             us USA
 2                     3    Paxten Aaronson             us USA
 3                     4  Keyliane Abdallah             fr FRA
 4                     5   Yunis Abdelhamid             ma MAR
 ...                 ...                ...                ...
 2961               2849    Martin Ødegaard             no NOR
 2962               2850        Milan Đurić             ba BIH
 2963                 Rk             Player             Nation
 2964               2851        Milan Đurić             ba BIH
 2965               2852   Mateusz Łęgowski             pl POL

      Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                     Pos              Squad                Comp
 0                    DF        Bournemouth  eng Premier League
 1                 MF,FW       Union Berlin       de Bundesliga
 2                    MF     Eint Frankfurt       de Bundesliga
 3                    FW          Marseille          fr Ligue 1
 4                    DF              Reims          fr Ligue 1
 ...                 ...                ...                 ...
 2961                 MF            Arsenal  eng Premier League
 2962                 FW      Hellas Verona          it Serie A
 2963                Pos              Squad                Comp
 2964                 FW              Monza          it Serie A
 2965                 MF        Salernitana          it Serie A

      Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Standard  ...  \
                     Age               Born                90s      Gls  ...
 0                    23               2000               13.7        0  ...
 1                    22               2000               14.1        2  ...
 2                    19               2003                1.1        0  ...
 3                    17               2006                0.0        0  ...
 4                    35               1987               30.9        4  ...
 ...                 ...                ...                ...      ...  ...
 2961                 24               1998               34.3        8  ...
 2962                 33               1990               13.4        5  ...
 2963                Age               Born                90s      Gls  ...
 2964                 33               1990               14.0        4  ...
 2965                 20               2003               12.7        0  ...

                           Expected                                \
       Dist  FK  PK  PKatt       xG  npxG  npxG/Sh  G-xG  np:G-xG
 0     23.9   0   0      0      0.0   0.0     0.02   0.0      0.0
 1     18.4   0   0      0      2.0   2.0     0.11   0.0      0.0
 2     15.1   0   0      0      0.1   0.1     0.06  -0.1     -0.1
 3      NaN   0   0      0      0.0   0.0      NaN   0.0      0.0
 4     15.0   0   1      1      3.4   2.6     0.13  +0.6     +0.4
 ...    ...  ..  ..    ...      ...   ...      ...   ...      ...
 2961  20.2   4   2      2      7.4   5.8     0.08  +0.6     +0.2
 2962  12.5   0   1      3      4.5   2.2     0.10  +0.5     +1.8
 2963  Dist  FK  PK  PKatt       xG  npxG  npxG/Sh  G-xG  np:G-xG
 2964  10.7   0   0      0      3.0   3.0     0.11  +1.0     +1.0
 2965  20.5   0   0      0      0.2   0.2     0.03  -0.2     -0.2

      Unnamed: 26_level_0
                  Matches
 0                Matches
 1                Matches
 2                Matches
 3                Matches
 4                Matches
 ...                  ...
 2961             Matches
 2962             Matches
 2963             Matches
 2964             Matches
 2965             Matches

 [2966 rows x 27 columns]]

In [2]:
df = pd.read_html(url_df)[0]
df.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player             Nation                Pos
0                  1         Max Aarons            eng ENG                 DF
1                  2   Brenden Aaronson             us USA              MF,FW
2                  3    Paxten Aaronson             us USA                 MF
3                  4  Keyliane Abdallah             fr FRA                 FW
4                  5   Yunis Abdelhamid             ma MAR                 DF

  Unnamed: 4_level_0  Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Squad                Comp                Age
0        Bournemouth  eng Premier League                 23
1       Union Berlin       de Bundesliga                 22
2     Eint Frankfurt       de Bundesliga                 19
3          Marseille          fr Ligue 1                 17
4              Reims          fr Ligue 1                 35

  Unnamed: 7_level_0 Unnamed: 8_level_0 Standard  ...                    \
                Born                90s      Gls  ...  Dist FK PK PKatt
0               2000               13.7        0  ...  23.9  0  0     0
1               2000               14.1        2  ...  18.4  0  0     0
2               2003                1.1        0  ...  15.1  0  0     0
3               2006                0.0        0  ...   NaN  0  0     0
4               1987               30.9        4  ...  15.0  0  1     1

  Expected                            Unnamed: 26_level_0
        xG npxG npxG/Sh  G-xG np:G-xG             Matches
0      0.0  0.0    0.02   0.0     0.0             Matches
1      2.0  2.0    0.11   0.0     0.0             Matches
2      0.1  0.1    0.06  -0.1    -0.1             Matches
3      0.0  0.0     NaN   0.0     0.0             Matches
4      3.4  2.6    0.13  +0.6    +0.4             Matches

[5 rows x 27 columns]

In [3]:
# creating a data with the same headers but without multi indexing
df.columns = [' '.join(col).strip() for col in df.columns]

df = df.reset_index(drop=True)
df.head()

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Player,Unnamed: 2_level_0 Nation,Unnamed: 3_level_0 Pos,Unnamed: 4_level_0 Squad,Unnamed: 5_level_0 Comp,Unnamed: 6_level_0 Age,Unnamed: 7_level_0 Born,Unnamed: 8_level_0 90s,Standard Gls,...,Standard Dist,Standard FK,Standard PK,Standard PKatt,Expected xG,Expected npxG,Expected npxG/Sh,Expected G-xG,Expected np:G-xG,Unnamed: 26_level_0 Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,0,...,23.9,0,0,0,0.0,0.0,0.02,0.0,0.0,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,2,...,18.4,0,0,0,2.0,2.0,0.11,0.0,0.0,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,0,...,15.1,0,0,0,0.1,0.1,0.06,-0.1,-0.1,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,0,...,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,4,...,15.0,0,1,1,3.4,2.6,0.13,+0.6,+0.4,Matches

In [4]:
# creating a list with new names
new_columns = []
for col in df.columns:
  if 'level_0' in col:
      new_col = col.split()[-1]  # takes the last name
  else:
      new_col = col
  new_columns.append(new_col)

# rename columns
df.columns = new_columns
df = df.fillna(0)

df.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Standard Gls,...,Standard Dist,Standard FK,Standard PK,Standard PKatt,Expected xG,Expected npxG,Expected npxG/Sh,Expected G-xG,Expected np:G-xG,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,0,...,23.9,0,0,0,0.0,0.0,0.02,0.0,0.0,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,2,...,18.4,0,0,0,2.0,2.0,0.11,0.0,0.0,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,0,...,15.1,0,0,0,0.1,0.1,0.06,-0.1,-0.1,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,0,...,0,0,0,0,0.0,0.0,0,0.0,0.0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,4,...,15.0,0,1,1,3.4,2.6,0.13,+0.6,+0.4,Matches

In [5]:
df['Age'] = df['Age'].str[:2]
df['Position_2'] = df['Pos'].str[3:]
df['Position'] = df['Pos'].str[:2]
df['Nation'] = df['Nation'].str.split(' ').str.get(1)
df['League'] = df['Comp'].str.split(' ').str.get(1)
df['League_'] = df['Comp'].str.split(' ').str.get(2)
df['League'] = df['League'] + ' ' + df['League_']
df = df.drop(columns=['League_', 'Comp', 'Rk', 'Pos','Matches'])

df['Position'] = df['Position'].replace({'MF': 'Midfielder', 'DF': 'Defender', 'FW': 'Forward', 'GK': 'Goalkeeper'})
df['Position_2'] = df['Position_2'].replace({'MF': 'Midfielder', 'DF': 'Defender',
                                                 'FW': 'Forward', 'GK': 'Goalkeeper'})
df['League'] = df['League'].fillna('Bundesliga')

In [9]:
df.to_csv('Data6.csv', encoding='utf-8', index = False)

In [8]:
# Load the CSV file
df = pd.read_csv('Data6.csv')

# Drop rows where the first column is empty
df.replace('', pd.NA, inplace=True)
df = df.dropna(subset=[df.columns[1]])

# Save the updated CSV file
df.to_csv('updated_file6.csv', index=False)

In [10]:
import pandas as pd

# Load the CSV files
df1 = pd.read_csv('megafile.csv')
df6 = pd.read_csv('updated_file6.csv')


merged_df = pd.merge(df1, df6, on=['Player', 'Squad', "Nation","Age","Born", "League", "Position", "Position_2", "90s"], how = 'outer')
# Save the merged data to a new CSV file
merged_df.to_csv('megafile.csv', index=False)